/** Internal visual reference. Specimens use production host styles and shared
 * behavior. All actions are local demonstrations; no account/site endpoint runs. */
import { componentGalleryShell } from './account-pages.ts';
import { UI_FONTS_CSS } from '../../shared/ui-fonts.js';
import { CUSTOM_SELECT_BOOT_SCRIPT, CUSTOM_SELECT_CSS } from '../../shared/custom-select.js';
import { ACTION_FEEDBACK_BOOT_SCRIPT } from '../../shared/action-feedback.js';
import { UI_MOTION_BOOT_SCRIPT } from '../../shared/ui-motion.js';

export const GALLERY_SECTIONS = ['fields', 'actions', 'tables', 'menus', 'dialogs', 'feedback'] as const;
export type GallerySection = typeof GALLERY_SECTIONS[number];
type Host = 'cloud' | 'builder';
export const galleryBaselineName = (name: string) => /^(cloud|builder)-(fields|actions|tables|menus|dialogs|feedback)-(1440|768)\.png$/.test(name) ? name : null;
const title = (s: string) => s[0].toUpperCase() + s.slice(1);
const closeIcon = '<svg aria-hidden="true" width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="m4 4 8 8M12 4l-8 8"/></svg>';
const pageIcon = '<svg aria-hidden="true" width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><rect x="3" y="2" width="10" height="12" rx="1.5"/><path d="M5.5 5h5m-5 3h5m-5 3h3"/></svg>';
const copy: Record<GallerySection, string> = {
  fields: 'Native fields and enhanced selects, in their actual host densities. Focus keeps the resting surface.',
  actions: 'Primary, secondary, destructive and disabled actions. Preview processing without saving anything.',
  tables: 'Neutral resting rows, compact cell padding and aligned headings. Hover a row to inspect its feedback.',
  menus: 'The same inset and item shape for links, buttons and destructive actions. Try the picker with your keyboard.',
  dialogs: 'One header, body and footer contract. Open the dialog, tab through it, then use Escape or Cancel.',
  feedback: 'Preview progress, success and recoverable failure using the shared notification system.'
};
const button = (host: Host, label: string, extra = '', attrs = '') => `<button type="button" class="${host === 'cloud' ? 'pc-btn' : 'btn'} ${extra} ${host === 'cloud' && extra.includes('danger') ? 'pc-delete-site-action' : ''}" ${attrs}>${label}</button>`;
const sample = (name: string, description: string, body: string) => `<section class="gallery-sample"><h2>${name}</h2><p class="pc-description gallery-sample-note">${description}</p>${body}</section>`;
const select = (id: string, cls: string, disabled = false) => `<select id="${id}" class="${cls}"${id === 'menu-select' ? ' aria-label="Current page"' : ''}${disabled ? ' disabled' : ''}><option value="home">Home</option><option value="contact">Plan your stay</option><option value="unavailable" disabled>Archived page (unavailable)</option></select>`;
function fields(host: Host) {
  if (host === 'cloud') return `<div class="gallery-grid">${sample('Full forms · 44px', 'Account, site settings and CMS forms.', `<div class="gallery-fields"><div class="pc-settings-field"><label for="site-name">Site name</label><input id="site-name" value="QA sample site" aria-describedby="name-help"><small id="name-help">This example is not saved.</small></div><div class="pc-settings-field"><label for="page-choice">Page</label>${select('page-choice', 'pc-sort')}</div></div>`)}${sample('Readonly and disabled', 'The surface identifies readonly values; disabled controls retain their size.', `<div class="gallery-fields"><div class="pc-settings-field"><label for="readonly-name">Public address</label><input id="readonly-name" value="pagecraft.example/sample" readonly></div><div class="pc-settings-field"><label for="disabled-name">Site name</label><input id="disabled-name" value="QA sample site" disabled></div><div class="pc-settings-field"><label for="disabled-choice">Page</label>${select('disabled-choice','pc-sort',true)}</div></div>`)}${sample('Member row · 32px', 'Role picker and row action share their compact height.', `<div class="pc-member-controls"><label class="pc-member-role" for="member-role"><span class="sr-only">Member role</span><select id="member-role"><option>Owner</option><option>Content editor</option></select></label>${button(host,'Remove','','data-demo="Member action previewed. No member was removed."')}</div>`)}${sample('Labels and validation', '12px input text; 11px field labels and help.', `<div class="pc-settings-field"><label for="invalid-name">Site name</label><input id="invalid-name" aria-invalid="true" aria-describedby="name-error" value=""><small id="name-error" class="gallery-error">Enter a site name to continue.</small></div>`)}</div>`;
  const fieldGroup = (id: string) => `<div class="f"><label for="${id}-name">Page name</label><input class="ctl" id="${id}-name" value="Plan your stay"></div><div class="f"><label for="${id}-page">Page</label>${select(id+'-page','ctl')}</div>`;
  return `<div class="gallery-grid">${sample('Editor fields · 37px','Inspector panels and builder dialogs.',`${fieldGroup('editor')}<div class="f"><label for="description">Meta description</label><textarea class="ctl" id="description">A short description of the sample page.</textarea></div>`)}${sample('Dense rows · 32px','Typography and inline editor controls.',`<div class="repeater-body">${fieldGroup('dense')}<div class="f"><label for="disabled-editor">Disabled value</label><input id="disabled-editor" class="ctl" value="Inherited value" disabled></div></div>`)}${sample('CMS forms · 44px','Full entry editing uses the spacious form density.',`<div class="cms-workspace">${fieldGroup('cms')}</div>`)}${sample('CMS schema · 36px','Names and types stay paired; row actions wrap together at tablet widths.',`<div class="cms-workspace"><div class="cms-schema"><div class="cms-field"><label for="schema-name">Collection name</label><input class="ctl" id="schema-name" value="Sample collection"></div><div class="cms-schema-field"><div class="cms-schema-inputs"><label for="schema-field">Field name<input class="ctl" id="schema-field" value="Title"></label><label for="schema-type">Type<select class="ctl" id="schema-type"><option>Text</option><option>Image</option></select></label><label class="cms-check"><input type="checkbox" checked>Required</label></div><div class="cms-actions">${button(host,'↑','','aria-label="Move sample field up" disabled')}${button(host,closeIcon,'','aria-label="Remove sample field" data-demo="Field action previewed. No schema was changed."')}</div></div></div></div>`)}</div>`;
}
function actions(host: Host) {
  const compactPending=button(host,closeIcon,host==='cloud'?'pc-iconbtn':'iconbtn','aria-label="Removing image…" aria-busy="true" data-pc-pending data-pc-pending-icon disabled');
  return sample('Action family','Hover and keyboard focus use the shared semantic treatment.',`<div class="gallery-action-row">${button(host,'Save changes','primary','data-demo="Save preview complete. Nothing was saved."')}${button(host,'Cancel','','data-demo="Preview cancelled."')}${button(host,'Delete sample','danger','data-demo="Delete preview only. Nothing was deleted."')}${button(host,'Unavailable','','disabled')}</div>`)+sample('Processing and recovery','Text actions retain their label; compact icon actions keep their original box while busy.',`<div class="gallery-action-row">${button(host,'Start processing','primary','id="processing" data-start')}${button(host,'Complete successfully','','data-finish="success" disabled')}${button(host,'Simulate failure','','data-finish="error" disabled')}${compactPending}</div><p class="pc-description">The action label and disabled state are restored after either result.</p>`)+sample('Disclosure and panel motion','Entrances use 180ms; exits use 120ms. Reduced-motion preferences complete immediately.',`<div class="gallery-action-row">${button(host,'Toggle details','','data-motion-disclosure aria-expanded="false" aria-controls="motion-details"')}${button(host,'Change panel','','data-motion-panel')}</div><div class="gallery-motion-panel" id="motion-panel-a">Current panel</div><div class="gallery-motion-panel" id="motion-panel-b" hidden>Next panel</div><div class="gallery-motion-panel" id="motion-details" hidden>Additional settings remain mounted until their exit completes.</div>`);
}
function tables(host: Host) {
  const listRoles = sample('List actions and empty collections','Heading actions are 37px; pagination is 32px. Empty lists keep the same leading edge.',`<div class="${host==='cloud'?'':'cms-workspace'}"><div class="pc-heading-actions">${button(host,'Edit collection','','data-demo="Heading action preview only."')}${button(host,'New entry','primary','data-demo="New entry preview only."')}</div><div class="pc-list-empty"><strong>No entries yet</strong><p>Create your first entry.</p></div><nav class="pc-pagination" aria-label="Sample pages">${button(host,'Previous','','disabled')}<span>Page 1 of 2 · 26 entries</span>${button(host,'Next','','data-demo="Pagination preview only."')}</nav></div>`);
  if(host==='cloud') return sample('Inbox rows','The heading aligns with the first icon. Links add no extra cell inset.',`<table class="pc-sub-table"><thead><tr><th>Form</th><th>Page</th><th>Entries</th><th>Actions</th></tr></thead><tbody>${['Contact form','Booking inquiry'].map((name,i)=>`<tr><td><a class="pc-form-link" href="#table-preview" data-demo="Row opened in preview only.">${pageIcon}${name}</a></td><td>${i?'Plan your stay':'Home'}</td><td>${i?'0':'3'}</td><td>${button(host,'View','','data-demo="Entry preview opened. No site data was loaded."')}</td></tr>`).join('')}</tbody></table>`)+sample('Empty result','Same column spacing when a filter has no matches.',`<table class="pc-sub-table"><thead><tr><th>Entry</th><th>Date</th><th>Status</th></tr></thead><tbody><tr><td colspan="3">No matching entries.</td></tr></tbody></table>`)+listRoles;
  return sample('Pages rows','Current pages keep the normal surface. Green row feedback is hover-only.',`<div class="pages-workspace"><div class="pages-list-head"><span>Page</span><span>Path</span><span>Type</span><span>Actions</span></div><div class="pagelist">${['Home','Plan your stay'].map((name,i)=>`<div class="pagerow ${i?'':'on'}"><button class="pagerow-main" data-demo="Page preview only.">${pageIcon}<span class="pn">${name}</span></button><span class="page-path">${i?'/contact':'/'}</span><span class="page-kind">${i?'Page':'Front page'}</span>${button(host,'Settings & SEO','tiny','data-demo="Settings preview only."')}<span></span></div>`).join('')}</div></div>`)+sample('CMS entry rows','Content can wrap while the row action retains its size.',`<div class="cms-workspace"><div class="cms-entry-row"><button class="cms-entry-open" data-demo="CMS preview only."><b>Sample entry</b><small>Draft content</small></button><span>Draft</span>${button(host,closeIcon,'','aria-label="Remove sample entry" data-demo="No entry was removed."')}</div></div>`)+listRoles;
}
function menus(host: Host) {
  return `<div class="gallery-grid">${sample('Menu items','6px panel inset, 4px item radius and identical link/button padding.',`<div class="pc-menu gallery-menu" role="menu" aria-label="Sample site actions"><a href="#manage" class="pc-menu-item" role="menuitem" data-demo="Manage preview only.">Manage site</a><button class="pc-menu-item" role="menuitem" data-demo="Copy preview only. Your clipboard is unchanged.">Copy public link</button><div class="pc-menu-divider" role="separator"></div><button class="pc-menu-item danger" role="menuitem" data-demo="Delete preview only. Nothing was deleted.">Delete site</button><button class="pc-menu-item" role="menuitem" disabled>Unavailable action</button></div>`)}${sample('Native select contract','Arrow keys browse, Enter selects and Escape cancels. Unavailable options cannot be selected.',host==='cloud'?`<div class="pc-settings-field"><label for="menu-select">Current page</label>${select('menu-select','pc-sort')}</div>`:`<div class="pc-toolbar-context"><span class="pill page-switcher">${select('menu-select','')}</span></div>`)} </div>`;
}
function dialogs(host: Host) {
  return sample('Dialog anatomy','24px body inset, 16px vertical header/footer inset, 8px action gap and 32px close.',`<div class="gallery-action-row">${button(host,'Open dialog','primary','data-dialog="standard"')}${button(host,'Open without footer','','data-dialog="empty"')}${button(host,'Open destructive dialog','danger','data-dialog="danger"')}</div><p class="pc-description">Values remain while the dialog is open across resizing. Cancel and Escape return focus to the opener.</p><dialog class="pc-dialog ${host==='cloud'?'pc-delete-dialog':'modal'} gallery-dialog" id="sample-dialog" aria-labelledby="sample-dialog-title"><header class="pc-dialog-head"><h2 class="pc-dialog-title" id="sample-dialog-title">Edit sample</h2>${button(host,closeIcon,'pc-dialog-close','aria-label="Close dialog" data-close')}</header><div class="pc-dialog-body"><p class="pc-dialog-description" id="dialog-description">This is a local example. No account or site data will change.</p><div class="${host==='cloud'?'pc-settings-field':'f'}"><label for="dialog-name">Sample name</label><input class="${host==='cloud'?'':'ctl'}" id="dialog-name" value="Sample page"></div></div><footer class="pc-dialog-foot" id="sample-dialog-foot">${button(host,'Cancel','','data-close')}${button(host,'Save sample','primary','data-dialog-save')}</footer></dialog>`);
}
function feedback(host: Host) {
  return sample('Notifications','Progress and errors remain until resolved or dismissed. Success uses status; failures use alert.',`<div class="gallery-action-row">${button(host,'Show success','','data-notice="success"')}${button(host,'Show error','','data-notice="error"')}${button(host,'Show progress','','data-notice="progress"')}${button(host,'Dismiss preview','','data-dismiss')}</div>`)+sample('Recoverable refresh failure','Retain the previous result and offer retry; successful background refresh has no completion banner.',`<div class="pc-refresh-status" data-tone="error" role="alert" id="refresh-error">Could not refresh the preview. The previous result is still shown.</div><div class="gallery-action-row">${button(host,'Retry refresh','','data-retry')}</div><p class="pc-caption" id="previous-result">Sample inbox · 3 entries</p>`);
}
const renderers = { fields, actions, tables, menus, dialogs, feedback };
function edgeCase(host: Host, section: GallerySection) {
  const fieldClass = host === 'cloud' ? 'pc-settings-field' : 'f';
  const controlClass = host === 'cloud' ? '' : 'ctl';
  const longName = 'Annual community workshop and accessibility review';
  const cases: Record<GallerySection, string> = {
    fields: `<div class="${fieldClass}"><label for="long-example">Description shown when a visitor shares this page with their team</label><textarea class="${controlClass}" id="long-example" aria-describedby="long-help">${longName}. A longer description wraps naturally and keeps the field aligned with its label and supporting text.</textarea><small id="long-help">Use a concise description. Longer help text should wrap without changing the spacing between adjacent fields.</small></div>`,
    actions: `<div class="gallery-action-row">${button(host,'Review changes across selected pages','primary','data-demo="Review action previewed. Nothing was published."')}${button(host,'Waiting for the current upload to finish','','disabled')}</div>`,
    tables: host === 'cloud'
      ? `<table class="pc-sub-table"><thead><tr><th>Form</th><th>Page</th><th>Actions</th></tr></thead><tbody><tr><td><a class="pc-form-link" href="#long-form" data-demo="Long row preview only.">${pageIcon}<span>${longName}</span></a></td><td>Community events and resources</td><td>${button(host,'View','','data-demo="Detail preview only."')}</td></tr></tbody></table>`
      : `<div class="cms-workspace"><nav class="cms-collections gallery-nav-example" aria-label="Long collection names"><button class="btn block primary" data-demo="Collection navigation preview only.">Community workshops, events and accessibility resources<span>27</span></button></nav><div class="cms-entry-row"><button class="cms-entry-open" data-demo="Long entry preview only."><b>${longName}</b><small>Draft entry with a longer description that wraps onto additional lines.</small></button><span>Draft</span>${button(host,closeIcon,'','aria-label="Remove long sample entry" disabled')}</div></div>`,
    menus: `<div class="pc-menu gallery-menu" role="menu" aria-label="Additional menu states"><button class="pc-menu-item" role="menuitem" data-demo="Draft review preview only.">Review changes before publishing</button><div class="pc-menu-divider" role="separator"></div><button class="pc-menu-item danger" role="menuitem" disabled>Remove selected unused images</button></div>`,
    dialogs: `<div class="pc-list-empty"><strong>No matching pages</strong><p>Try a shorter name or clear the search to see all pages.</p>${button(host,'Clear sample search','','data-demo="Search recovery previewed. No page data was loaded."')}</div>`,
    feedback: `<div class="pc-refresh-status" data-tone="error" role="alert">The latest content could not be loaded. Your saved content is still available; try refreshing again.</div><div class="gallery-action-row">${button(host,'Retry loading content','','data-demo="Retry preview complete. No request was sent."')}</div>`
  };
  return sample('Long content and recovery', 'Fictional edge cases use the same production components and density rules.', `<div data-gallery-edge-case="${section}">${cases[section]}</div>`);
}
const GALLERY_CSS = `
/* Gallery composition only. Specimen controls keep their production rules. */
html,body{height:auto;min-height:100%;overflow:auto;background:#fff;color:#111311}
.gallery{font:var(--pc-type-input);min-height:100vh;background:#fff;color:#111311}
.gallery-top{display:flex;align-items:center;gap:24px;padding:16px 24px;border-bottom:1px solid var(--pc-border)}
.gallery,.gallery#app{display:grid;grid-template-rows:auto 1fr;height:auto;overflow:visible}.gallery-nav a,.gallery-top>a,.gallery-heading a{color:inherit}.gallery-sample>.pages-workspace{min-height:0}.gallery-sample .pagelist{padding-bottom:0}
.gallery-top strong{font-size:var(--pc-text-panel);font-weight:600}.gallery-top>a{margin-left:auto;font:var(--pc-type-control)}
.gallery-shell{display:grid;grid-template-columns:172px minmax(0,1fr);min-height:0}
.gallery-nav{padding:24px 16px;border-right:1px solid var(--pc-border);display:flex;flex-direction:column;gap:4px;align-items:stretch}
.gallery-nav a{padding:8px 12px;border-radius:var(--pc-control-radius);font:var(--pc-type-control);text-decoration:none}.gallery-nav a[aria-current=page]{background:var(--pc-selection-bg);color:var(--pc-selection-text)}
.gallery-nav a:hover{background:var(--pc-hover-bg)}
.gallery-content{padding:28px 32px;min-width:0}.gallery-heading{display:flex;justify-content:space-between;align-items:start;gap:24px;margin-bottom:24px}.gallery-heading h1{font-size:var(--pc-text-workspace);font-weight:700;line-height:1.3;letter-spacing:-.02em;margin:0 0 8px}.gallery-heading p{font:var(--pc-type-input);color:#4b504b;max-width:70ch;margin:0}.gallery-heading a{white-space:nowrap}
.gallery-hosts{display:flex;gap:8px}.gallery-hosts a{color:#4b504b;font:var(--pc-type-control);text-decoration:none;padding:6px 8px;border-radius:var(--pc-control-radius)}.gallery-hosts a[aria-current=page]{background:var(--pc-selection-bg);color:var(--pc-selection-text)}
.gallery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:32px}.gallery-sample{min-width:0;margin:0 0 28px}.gallery-sample h2{font-size:var(--pc-text-section);font-weight:600;line-height:1.4;margin:0 0 8px;letter-spacing:-.015em}.gallery-sample-note{margin:0 0 20px;color:#4b504b;max-width:65ch}.gallery-fields{display:grid;gap:var(--pc-field-gap)}
.gallery-action-row{display:flex;flex-wrap:wrap;align-items:center;gap:var(--pc-action-gap);margin:0 0 16px}.pc-settings-field .gallery-error{color:var(--pc-danger,#a8402f)}
.gallery-motion-panel{padding:12px;border:1px solid var(--pc-border);border-radius:var(--pc-control-radius);background:var(--pc-surface-subtle);margin-top:8px}
.gallery-nav-example{max-width:220px;margin-bottom:16px}
.gallery-menu{width:240px;background:var(--pc-popup-bg);box-shadow:0 18px 42px -18px #1113116b}.gallery-dialog{width:min(560px,calc(100vw - 48px));margin:auto}.gallery-dialog[open]{display:flex;flex-direction:column}.gallery-dialog:not([open]){display:none}.gallery-dialog.modal{position:fixed;inset:0}
.gallery-footnote{border-top:1px solid var(--pc-border);padding-top:16px;margin-top:12px;color:#4b504b;font:var(--pc-type-description)}@media(max-width:1050px){.gallery-content{padding:24px 20px}.gallery-shell{grid-template-columns:144px minmax(0,1fr)}.gallery-nav{padding:24px 8px}.gallery-grid{grid-template-columns:1fr;gap:8px}.gallery-heading{flex-wrap:wrap}.gallery-top{padding-inline:20px}}
`;
const GALLERY_SCRIPT = `(()=>{
  const host=document.body.dataset.galleryHost, section=document.body.dataset.gallerySection;
  const baseline=document.getElementById('gallery-baseline');
  const updateBaseline=()=>{const width=innerWidth<1050?768:1440;baseline.href='/internal/components/baselines/'+host+'-'+section+'-'+width+'.png';baseline.textContent='Open '+width+'px baseline';};
  updateBaseline();addEventListener('resize',updateBaseline);
  document.addEventListener('submit',e=>e.preventDefault());
  document.querySelectorAll('[data-demo]').forEach(node=>node.addEventListener('click',e=>{e.preventDefault();window.__pcFeedback.notify(node.dataset.demo,{tone:'info'});}));
  let job,notice;const process=document.querySelector('[data-start]'),finish=[...document.querySelectorAll('[data-finish]')];
  process?.addEventListener('click',()=>{job=window.__pcFeedback.begin(process,'Processing preview…','gallery-preview');finish.forEach(b=>b.disabled=false);});
  finish.forEach(b=>b.addEventListener('click',()=>{if(!job)return;job[b.dataset.finish](b.dataset.finish==='error'?'Preview failed. Try Start processing again.':'Preview complete. Nothing was saved.');job=null;finish.forEach(b=>b.disabled=true);}));
  document.querySelectorAll('[data-notice]').forEach(b=>b.addEventListener('click',()=>{notice?.dismiss();const tone=b.dataset.notice;notice=window.__pcFeedback.notify({success:'Preview saved. No site was changed.',error:'Preview could not finish. Dismiss this message and retry.',progress:'Processing preview…'}[tone],{id:'gallery-notice',tone,duration:0});}));
  document.querySelector('[data-dismiss]')?.addEventListener('click',()=>notice?.dismiss());
  document.querySelector('[data-retry]')?.addEventListener('click',e=>{document.getElementById('refresh-error').hidden=true;e.currentTarget.disabled=true;});
  document.querySelector('[data-motion-disclosure]')?.addEventListener('click',e=>{const panel=document.getElementById('motion-details'),open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));if(open)window.__pcMotion.exit(panel,{kind:'panel'});else window.__pcMotion.enter(panel,{kind:'panel'});});
  document.querySelector('[data-motion-panel]')?.addEventListener('click',async()=>{const a=document.getElementById('motion-panel-a'),b=document.getElementById('motion-panel-b'),from=a.hidden?b:a,to=a.hidden?a:b;await window.__pcMotion.exit(from,{kind:'panel'});window.__pcMotion.enter(to,{kind:'panel'});});
  const dialog=document.getElementById('sample-dialog');let opener,footer;
  if(dialog){footer=dialog.querySelector('footer').innerHTML;
    document.querySelectorAll('[data-dialog]').forEach(b=>b.addEventListener('click',()=>{opener=b;const kind=b.dataset.dialog;dialog.querySelector('h2').textContent=kind==='danger'?'Delete sample':'Edit sample';dialog.querySelector('footer').innerHTML=kind==='empty'?'':footer;const save=dialog.querySelector('[data-dialog-save]');if(save){save.textContent=kind==='danger'?'Delete sample':'Save sample';save.classList.toggle('danger',kind==='danger');save.classList.toggle('pc-delete-site-action',kind==='danger');save.classList.toggle('primary',kind!=='danger');}dialog.showModal();}));
    dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.matches('[data-close],[data-dialog-save]'))dialog.close();});
    dialog.addEventListener('close',()=>opener?.focus());
  }
  // Escape closes the example menu without leaving focus in a hidden descendant.
  document.querySelectorAll('[role=menu]').forEach(menu=>menu.addEventListener('keydown',e=>{const items=[...menu.querySelectorAll('[role=menuitem]:not(:disabled)')];const i=items.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}}));
  document.fonts.ready.then(()=>{document.documentElement.dataset.galleryReady='true';});
})();`;
export function componentGalleryPage(editorHtml: string, rawHost?: string, rawSection?: string) {
  const host: Host = rawHost === 'builder' ? 'builder' : 'cloud';
  const section: GallerySection = GALLERY_SECTIONS.includes(rawSection as GallerySection) ? rawSection as GallerySection : 'fields';
  const href=(h:Host,s:GallerySection)=>`/internal/components?host=${h}&amp;section=${s}`;
  const body=`<main class="gallery ${host==='cloud'?'dashboard-app':''}" ${host==='builder'?'id="app"':''}><header class="gallery-top"><strong>Component gallery</strong><nav class="gallery-hosts" aria-label="Style source">${(['cloud','builder'] as Host[]).map(h=>`<a href="${href(h,section)}" ${h===host?'aria-current="page"':''}>${title(h)}</a>`).join('')}</nav><a href="/">Back to sites</a></header><div class="gallery-shell"><nav class="gallery-nav" aria-label="Component families">${GALLERY_SECTIONS.map(s=>`<a href="${href(host,s)}" ${s===section?'aria-current="page"':''}>${title(s)}</a>`).join('')}</nav><div class="gallery-content"><header class="gallery-heading"><div><h1>${title(section)}</h1><p>${copy[section]}</p></div><a id="gallery-baseline" href="/internal/components/baselines/${host}-${section}-1440.png" target="_blank" rel="noopener">Open baseline</a></header>${renderers[section](host)}<p class="gallery-footnote">Internal reference · Local sample values only. Actions do not save, publish, connect, delete or change your clipboard.</p></div></div></main>`;
  // The builder's compiled style blocks include the real cascade. Omit embedded
  // fonts in favour of the same allowlisted brand files used by Cloud.
  const editorStyles=[...editorHtml.matchAll(/<style\b([^>]*)>([\s\S]*?)<\/style>/gi)].filter(m=>!m[1].includes('pc-fonts')).map(m=>m[0]).join('\n');
  let html=host==='cloud'?componentGalleryShell(body):`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Component gallery — Pagecraft</title><style>${UI_FONTS_CSS}</style>${editorStyles}<style>${CUSTOM_SELECT_CSS}</style></head><body>${body}<script>${UI_MOTION_BOOT_SCRIPT}${ACTION_FEEDBACK_BOOT_SCRIPT}${CUSTOM_SELECT_BOOT_SCRIPT}</script></body></html>`;
  html=html.replace('<p class="gallery-footnote">',`${edgeCase(host,section)}<p class="gallery-footnote">`);
  html=html.replace('</head>',`<meta name="robots" content="noindex,nofollow"><style id="gallery-layout">${GALLERY_CSS}</style></head>`).replace('<body>',`<body data-gallery-host="${host}" data-gallery-section="${section}">`);
  return html.replace('</body>',`<script>${GALLERY_SCRIPT}</script></body>`);
}
